---
author: "Owen Liu"
date: "August 17, 2016"
output: html_document
---

The model selection exercise peaks at nine variables. There are a lot of interesting observations from this exercise:

* The best model has a skill of greater than 0.75 and consists of a reconstruction with four physical variables of two types (MEI/El Nino and significant wave height), and five biological variables from four species (*Strogylocentrotus fransciscanus*, *S. purpuratus*, *Megastreaea undosa*, and *Patiria miniata*)
* *Macrocystis pyrifera* itself does not show up as a signficant variable. The time series reconstructed with one lag of *M. pyrifera* was the last-selected variable, after the peak in predictive ability
* The two first selected variables relate to significant wave height, confirming other findings. Together, wave dynamics and its first lag produce predictions with a correlation of >0.5 with observations.
* Three of the top five selected variables are physical, but the other two are related to biological variables, specifically urchin dynamics. However, the selected urchin variables are lags, potentially suggesting that adult *M. pyrifera* dynamics are determined by urchin effects on younger life stages of *M. pyrifera* (e.g., recruitment and juvenile growth), rather than contemporaneous effects of urchins on adult kelps.

The best multivariate models for each species strictly and often greatly outperform the best univariate (self-predicting) models.  All multivariate models with the exception of the model for *Pisaster giganteus* exceed a model skill ($\rho$) of 0.5.

$t_p$